Added Tutorials for Google Batch
STRIDES/NIHCloudLabGCP pull request #39
Opened 2023-08-07 16:54 UTC by zyosufzai

## Pull Request Template

### Description

*Added tutorials for using Google Batch based on the LS API Tutorials, added usage of Google Batch in ReadMe, added warnings in the LS API tutorials that the product is depreciated and linked to the Google Batch tutorials, and added warning in Snakemake tutorials that LS API is depreciated and to check Snakemake documentation for when they have instuctions on Google Batch (right now they only use LS API same goes for Cromwell)*

### Assignee

*Assignees: @kyleoconnell-NIH *

## PR checklist
*Please ensure the following:*
- [X ] This comment contains a description of changes (with reason).
- [ X] All changes were tested.
- [X ] If you've fixed a bug mention the issue number/name.
- [ X] Apply approriate tags (e.g. documentation, bug)

2023-08-15 18:04 UTC, kyleoconnell-NIH requested changes
Did you also convert the Nextflow Tutorial under LS API? to Batch?

2023-08-15 18:04 UTC, kyleoconnell-NIH commented on tutorials/notebooks/GoogleBatch/nextflow/batch_images/service_account_4.jpg
Can you black out the Principal and the project name?

2023-08-15 18:04 UTC, kyleoconnell-NIH commented on tutorials/notebooks/GoogleBatch/nextflow/batch_images/service_account_1.jpeg
Block out the project name

2023-08-15 18:04 UTC, kyleoconnell-NIH commented on tutorials/notebooks/GoogleBatch/nextflow/batch_images/Job_l.png
Block project name

2023-08-15 18:04 UTC, kyleoconnell-NIH commented on tutorials/notebooks/LifeSciencesAPI/snakemake/LS_API_Snakemake.ipynb
> +   "display_name": "PySpark (Local)",
Why are we using PySpark Kernel?

2023-08-18 11:57 UTC, zyosufzai commented
> Did you also convert the Nextflow Tutorial under LS API? to Batch?

yes I added a Batch tutorials for Nextflow and added a warning in the LS API that it is depreciated and linked back to the Batch tutorials. I didn't remove the LS API tutorials because technically you can still use LS API until 2025

2023-08-21 13:22 UTC, kyleoconnell-NIH approved these changes

2023-08-21 15:47 UTC, zyosufzai commented on README.md
> +Vertex AI not only has the capabilities to create Jupyter notebooks but also generative AI models. Some examples of what generative AI models are capabile of are extracting wanted information from te
resolved with the latest push

2023-08-21 16:03 UTC, petersonjdNIH commented on tutorials/notebooks/GenAI/GenAIStudioGCP.ipynb
@zyosufzai Is this deep link to the Google Cloud Console safe for the public, or is it deep linking to something that only belongs to NIH?

2023-08-21 18:41 UTC, zyosufzai commented on tutorials/notebooks/GenAI/GenAIStudioGCP.ipynb
Do you mean this link 'https://console.cloud.google.com/vertex-ai/generative/language?_ga=2.182664366.923116401.1692009977-1042353744.1691708677'? No this is not NIH specific it is a link to the Generative AI Studio. If you'd like I can instead replace this with instruction on how to get to this page instead (e.g. Generative AI Studio > Language > Article Summary)

2023-08-21 22:52 UTC, petersonjdNIH approved these changes

2023-08-22 14:42 UTC, merged