I am committing GCP_RAG_for_Structure_Data.ipynb
STRIDES/NIHCloudLabGCP pull request #67
Opened 2024-10-18 13:57 UTC by cetrarom2

## Pull Request Template

### Description

*This tutorial creates a BigQuery dataset and a table where our data file is uploaded.  Also, it describes how set up a chatbot sql agent which allows the end user to enter a query using natural language text to extract the information requested.*

### Assignee

*Assignees: @cetrarom2 -NIH*

## PR checklist
*Please ensure the following:*
- [ ] This comment contains a description of changes (with reason).
- [ ] All changes were tested.
- [ ] If you've fixed a bug mention the issue number/name.
- [ ] Apply approriate tags (e.g. documentation, bug)

2024-10-21 16:39 UTC, zbyosufzai reviewed
please see comments

2024-10-21 19:18 UTC, cetrarom2 commented on notebooks/GenAI/GCP_RAG_for_Structure_Data.ipynb
> +    "schema = [\n",
I am not sure where I should insert this code.

2024-10-21 19:18 UTC, cetrarom2 commented on notebooks/GenAI/GCP_RAG_for_Structure_Data.ipynb
> +    "We can perform a similar check to confirm that the table we created is located within the appropriate dataset."
Done.

2024-10-21 19:27 UTC, cetrarom2 commented on notebooks/GenAI/GCP_RAG_for_Structure_Data.ipynb
> +    "my_bucket = bucket\n",
Ok.

2024-10-21 19:43 UTC, cetrarom2 commented on notebooks/GenAI/GCP_RAG_for_Structure_Data.ipynb
> +    "service_account_file = \"<Service_Account_File>\" # Change to where your service account key file is located\n",
Done.

2024-10-21 20:13 UTC, cetrarom2 commented on notebooks/GenAI/GCP_RAG_for_Structure_Data.ipynb
> +    "Next, we import the __ChatVertexAI__ agent from Langchain and configure it with the appropriate hyperparameters. In this instance, we are using the __gemini-1.5-pro__ LLM model, after which we c
I explained about agents and the LLM models in the PREREQUISITES section.

2024-10-21 20:19 UTC, cetrarom2 commented on notebooks/GenAI/GCP_RAG_for_Structure_Data.ipynb
> +    "In this tutorial, we present a technique that leverages SQL databases. By formulating a query based on the user's request, the model submits this query to the database, providing comprehensive r
Done.

2024-10-21 20:29 UTC, cetrarom2 commented on notebooks/GenAI/GCP_RAG_for_Structure_Data.ipynb
> +    "Before we begin, you'll need to create a Vertex AI RAG Data Service Agent service account. To do this, go to the IAM section of the console. Ensure you check the box for \"Include Google-provide
I had issues to load data to the BigQuery table.  The error was related to permissions, but the actual issue was that all the fields on the data schema mode had to be NULLABLE and I didn't have them as NULLABLE.

2024-10-21 20:29 UTC, cetrarom2 commented on notebooks/GenAI/GCP_RAG_for_Structure_Data.ipynb
> +    "- How to use the langchain ChatVertexAI agent to extract information froim the table. \n"
Done.

2024-10-21 20:29 UTC, cetrarom2 commented on notebooks/GenAI/GCP_RAG_for_Structure_Data.ipynb
> +    " <li>Model for Chat: 5 request per day. Average Input and Output characters 5,000.</li>\n",
Done.

2024-10-21 20:29 UTC, cetrarom2 commented on notebooks/GenAI/GCP_RAG_for_Structure_Data.ipynb
> +    "Provide the names of the bucket name, source file name path, and destination blob name to upload the CSV source file to the bucket."
Done.

2024-10-21 20:29 UTC, cetrarom2 commented on notebooks/GenAI/GCP_RAG_for_Structure_Data.ipynb
> +    "Provide the names of the bucket name, source file name path, and destination blob name to upload the CSV source file to the bucket."
Done.

2024-10-21 20:30 UTC, cetrarom2 commented on notebooks/GenAI/GCP_RAG_for_Structure_Data.ipynb
> +    "from google.cloud import storage\n",
Cell has been replaced.

2024-10-21 20:30 UTC, cetrarom2 commented on notebooks/GenAI/GCP_RAG_for_Structure_Data.ipynb
> +    "dataset_id = project_id.'<Name of the Dataset>'\n",
Done

2024-10-21 20:30 UTC, cetrarom2 commented on notebooks/GenAI/GCP_RAG_for_Structure_Data.ipynb
> +    "table_id = project_id.dataset_id.\"<Table Name>\"\n",
Done.

2024-10-21 20:31 UTC, cetrarom2 commented on notebooks/GenAI/GCP_RAG_for_Structure_Data.ipynb
> +    "To interact with the BigQuery table using a Pythonic domain language, we utilize SQLAlchemy. SQLAlchemy is a Python SQL toolkit that enables developers to access and manage SQL databases, allowi
Done.

2024-10-21 20:31 UTC, cetrarom2 commented on notebooks/GenAI/GCP_RAG_for_Structure_Data.ipynb
> +    "Please remember to delete or stop your Jupyter notebook and delete your data store to prevent incurring charges. And if you have created any other services like buckets, please remember to delet
Done.

2024-10-23 17:52 UTC, zbyosufzai requested changes

2024-10-23 17:52 UTC, zbyosufzai commented on notebooks/GenAI/GCP_RAG_for_Structure_Data.ipynb
> +    " <li>Model for Chat: 5 request per day. Average Input and Output characters 5,000.</li>\n",
Please add in the price for one session in one day

2024-10-23 17:52 UTC, zbyosufzai commented on notebooks/GenAI/GCP_RAG_for_Structure_Data.ipynb
> +    "Provide the names of the bucket name, source file name path, and destination blob name to upload the CSV source file to the bucket."
add Kaggle dataset link and inform user that this is the dataset we used for this tutorial

2024-10-23 17:52 UTC, zbyosufzai commented on notebooks/GenAI/GCP_RAG_for_Structure_Data.ipynb
> +    "Provide the names of the bucket name, source file name path, and destination blob name to upload the CSV source file to the bucket."
please add these instructions when they are creating the bucket

2024-10-23 17:52 UTC, zbyosufzai commented on notebooks/GenAI/GCP_RAG_for_Structure_Data.ipynb
> +    "To upload the data from our file stored in the bucket, we first need to create a DataFrame. In this example, we will be using a file that contains health screening data."
df is a variable that doesn't seem to define anything please add it back and set the data to a data frame

2024-10-23 17:52 UTC, zbyosufzai commented on notebooks/GenAI/GCP_RAG_for_Structure_Data.ipynb
> +    "service_account_file = \"<Service_Account_File>\" # Change to where your service account key file is located\n",
change  `sqlalchemy_url = f'bigquery://{project_id}/{dataset}' ` to `sqlalchemy_url = f'bigquery://{project_id}/{dataset_name}'`

2024-10-23 17:52 UTC, zbyosufzai commented on images/.ipynb_checkpoints/gcp_rag_structure_data_01-checkpoint.png
try using in your terminal `git rm <file name>`

2024-10-23 17:53 UTC, zbyosufzai commented on notebooks/GenAI/GCP_RAG_for_Structure_Data.ipynb
> +    "Before we begin, you'll need to create a Vertex AI RAG Data Service Agent service account. To do this, go to the IAM section of the console. Ensure you check the box for \"Include Google-provide
not all users will have already set perms so if you looks at the service account sit will list the big query perms needed

2024-10-23 17:54 UTC, zbyosufzai commented on notebooks/GenAI/GCP_RAG_for_Structure_Data.ipynb
> +    "In this tutorial, we present a technique that leverages SQL databases. By formulating a query based on the user's request, the model submits this query to the database, providing comprehensive r
can you also say that its the agent that connects to the BQ and runs the query then it send the results to the model and the model only writes the conclusion or the output the user sees.

2024-10-23 19:43 UTC, cetrarom2 commented on notebooks/GenAI/GCP_RAG_for_Structure_Data.ipynb
> +    "In this tutorial, we present a technique that leverages SQL databases. By formulating a query based on the user's request, the model submits this query to the database, providing comprehensive r
Done

2024-10-23 19:43 UTC, cetrarom2 commented on notebooks/GenAI/GCP_RAG_for_Structure_Data.ipynb
> +    "Before we begin, you'll need to create a Vertex AI RAG Data Service Agent service account. To do this, go to the IAM section of the console. Ensure you check the box for \"Include Google-provide
Done

2024-10-23 19:47 UTC, cetrarom2 commented on notebooks/GenAI/GCP_RAG_for_Structure_Data.ipynb
> +    " <li>Model for Chat: 5 request per day. Average Input and Output characters 5,000.</li>\n",
I have checked the Google Price Calculator and there is not a way to get the estimated cost per session.  The estimated cost that I get is per month.

2024-10-23 19:55 UTC, cetrarom2 commented on notebooks/GenAI/GCP_RAG_for_Structure_Data.ipynb
> +    "Provide the names of the bucket name, source file name path, and destination blob name to upload the CSV source file to the bucket."
Done.

2024-10-23 19:58 UTC, cetrarom2 commented on notebooks/GenAI/GCP_RAG_for_Structure_Data.ipynb
> +    "service_account_file = \"<Service_Account_File>\" # Change to where your service account key file is located\n",
Done.

2024-10-23 19:59 UTC, cetrarom2 commented on images/.ipynb_checkpoints/gcp_rag_structure_data_01-checkpoint.png
Ok.

2024-10-23 20:00 UTC, cetrarom2 commented on notebooks/GenAI/.ipynb_checkpoints/GCP_RAG_for_Structure_Data-checkpoint.ipynb
N/A

2024-10-23 20:06 UTC, cetrarom2 commented on notebooks/GenAI/GCP_RAG_for_Structure_Data.ipynb
> +    "from google.cloud import storage\n",
N/A

2024-10-23 20:09 UTC, cetrarom2 commented on notebooks/GenAI/GCP_RAG_for_Structure_Data.ipynb
> +    "Provide the names of the bucket name, source file name path, and destination blob name to upload the CSV source file to the bucket."
Done.

2024-10-23 20:10 UTC, cetrarom2 commented on notebooks/GenAI/GCP_RAG_for_Structure_Data.ipynb
> +    "schema = [\n",
done.

2024-10-23 20:27 UTC, cetrarom2 commented on notebooks/GenAI/GCP_RAG_for_Structure_Data.ipynb
> +    "To upload the data from our file stored in the bucket, we first need to create a DataFrame. In this example, we will be using a file that contains health screening data."
A new cell was created where the dataframe is created containing the 'health screening' dataset. Done.

2025-01-10 18:58 UTC, merged